version: 0.1
logging_level: INFO

scenario:
  sectors: [E] # ,E+EV,E+BEV,E+BEV+V2G] # [ E+EV, E+BEV, E+BEV+V2G ]
  simpl: ['']
  lv: [1.0, 1.125, 1.25, 1.5, 2.0, 3.0]
  clusters: [45, 64, 90, 128, 181, 256] #, 362] # (2**np.r_[5.5:9:.5]).astype(int)
  opts: [Co2L-3H] #, LC-FL, LC-T, Ep-T, Co2L-T]

countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK'] 

snapshots:
  # arguments to pd.date_range
  start: "2013-01-01"
  end: "2014-01-01"
  closed: 'left' # end is not inclusive

enable:
  powerplantmatching: false
  prepare_links_p_nom: false

electricity:
  voltages: [220., 300., 380.]
  co2limit: 7.75e+7 # 0.05 * 3.1e9*0.5

  extendable_carriers:
    Generator: [OCGT]
    StorageUnit: [battery, H2] # [CAES]

  max_hours:
    battery: 6
    H2: 168

  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]

atlite:
  nprocesses: 4
  cutouts:
    europe-2013-era5:
      module: era5
      xs: [-12., 35.]
      ys: [72., 33.]
      years: [2013, 2013]
    europe-2013-sarah:
      module: sarah
      resolution: 0.2
      xs: [-12., 42.]
      ys: [65., 33.]
      years: [2013, 2013]

renewable:
  onwind:
    cutout: europe-2013-era5
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    # ScholzPhd Tab 4.3.1: 10MW/km^2
    capacity_per_sqm: 3
    # correction_factor: 0.93
    corine:
      #The selection of CORINE Land Cover [1] types that are allowed for wind and solar are based on [2] p.42 / p.28
      #
      #[1] https://www.eea.europa.eu/ds_resolveuid/C9RK15EA06
      #
      #[2] Scholz, Y. (2012). Renewable energy based electricity supply at low costs: development of the REMix model and application for Europe.
      grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
                   24, 25, 26, 27, 28, 29, 31, 32]
      distance: 1000
      distance_grid_codes: [1, 2, 3, 4, 5, 6]
      natura: true
  offwind:
    cutout: europe-2013-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    # ScholzPhd Tab 4.3.1: 10MW/km^2
    capacity_per_sqm: 3
    height_cutoff: 50
    # correction_factor: 0.93
    corine:
      grid_codes: [44, 255]
      natura: true
  solar:
    cutout: europe-2013-sarah
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    # ScholzPhd Tab 4.3.1: 170 MW/km^2
    capacity_per_sqm: 1.7
    correction_factor: 0.877
    corine:
      grid_codes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
      18, 19, 20, 26, 31, 32]
      natura: true
  hydro:
    cutout: europe-2013-era5
    carriers: [ror, PHS, hydro]
    PHS_max_hours: 6


lines:
  types:
    220.: "Al/St 240/40 2-bundle 220.0"
    300.: "Al/St 240/40 3-bundle 300.0"
    380.: "Al/St 240/40 4-bundle 380.0"

  s_max_pu: 0.7
  length_factor: 1.25
  with_under_construction: false

links:
  s_max_pu: 0.7
  with_under_construction: false

transformers:
  x: 0.1
  s_nom: 2000.
  type: ''

costs:
  year: 2030

  # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  discountrate: 0.07
  # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html # noqa: E501
  USD2013_to_EUR2013: 0.7532

  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   Wind: Bla
  marginal_cost: # 
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    battery: 0.

  emission_prices: # only used with the option Ep (emission prices)
    co2: 0.

solving:
  options:
    formulation: kirchhoff
    clip_p_max_pu: 1.e-2
    load_shedding: true
    noisy_costs: true
    min_iterations: 4
    max_iterations: 6
    # max_iterations: 1
    # nhours: 10
  solver:
    name: gurobi
    threads: 4
    method: 2
    crossover: 0 # -1 (Choose freely)
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    LogToConsole: 0
    OutputFlag: 1

plotting:
  map:
    figsize: [7, 7]
    boundaries: [16, -35, 33, -22]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3 # 1.e+3  #3.e+3

  costs_max: 800

  vre_techs: ["Wind", "PV"]
  conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
  storage_techs: ["Hydro", "CAES", "Battery", "Pumped storage", "Hydro+PS"]
  store_techs: ["Li ion", "water tanks"]
  load_carriers: ["AC load", "heat load", "Li ion load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"] 
  heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
               "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
               "central CHP electric", "central gas boiler"]
  heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
  tech_colors:
    onwind: "xkcd:azure"
    offwind: "blue"
    hydro: "g"
    ror: "g"
    PHS: "g"
    hydro+PHS: "g"
    solar: "yellow"
    OCGT: "brown"
    OCGT marginal: "sandybrown"
    OCGT-heat: "orange"
    central gas boiler: "orange"
    gas boiler: "orange"
    gas boilers: "orange"
    gas boiler marginal: "orange"
    gas: "brown"
    lines: "k"
    AC line: "k"
    AC-AC: "k"
    transmission lines: "k"
    H2: "m"
    hydrogen storage: "m"
    battery: "slategray"
    battery storage: "slategray"
    CAES: "lightgray"
    nuclear: "r"
    nuclear marginal: "r"
    coal: "k"
    coal marginal: "k"
    lignite: "grey"
    lignite marginal: "grey"
    CCGT: "orange"
    CCGT marginal: "orange"
    diesel: "darkred"
    diesel marginal: "darkred"
    heat pumps: "green"
    heat pump: "green"
    central heat pump: "green"
    resistive heater: "pink"
    central resistive heater: "pink"
    Sabatier: "turquoise"
    water tanks: "w"
    CHP: "r"
    CHP heat: "r"
    CHP electric: "r"
    central CHP heat: "r"
    central CHP electric: "r"
    Pumped storage: "g"
    Ambient: "k"
    AC load: "b"
    Heat load: "r"
    Li ion load: "grey"
    heat: "r"
    Li ion: "grey"
    district heating: "#CC4E5C"
  nice_names:
    # OCGT: "Gas"
    # OCGT marginal: "Gas (marginal)"
    offwind: "offshore wind"
    onwind: "onshore wind"
    battery: "Battery storage"
    lines: "Transmission lines"
    AC line: "AC lines"
    AC-AC: "DC lines"
    ror: "Run of river"
  nice_names_n:
    offwind: "offshore\nwind"
    onwind: "onshore\nwind"
    # OCGT: "Gas"
    H2: "Hydrogen\nstorage"
    # OCGT marginal: "Gas (marginal)"
    lines: "transmission\nlines"
    ror: "run of river"
