name: pypsa-doc
channels:
- conda-forge
dependencies:
- python>=3.9
- pip
- python
- six
- numpy
- scipy
- pandas>=1.1.0
- xarray
- netcdf4
- pytables
- matplotlib
- networkx>=2
- cartopy>=0.16
- geopandas>=0.9
- deprecation
- seaborn
- pandoc
- ipykernel   # for executing nbs
- scikit-learn  # for spatial clustering
- linopy>=0.3.9

- pip:
  - .
  - sphinx<6
  - sphinx-book-theme
  - nbsphinx
  - nbsphinx_link
  - highspy
  - myst-parser
  - sphinxcontrib.bibtex
  - highspy>=1.5.3
