name: pypsa
channels:
- conda-forge
dependencies:
- python>=3.11

# Copy from regular environment.yaml
- numpy
- scipy
- pandas>=0.24.0
- xarray
- netcdf4
- libnetcdf
- pytables
- matplotlib
- networkx>=1.10
- cartopy>=0.16
- geopandas>=0.9
- glpk
- linopy>=0.2
- deprecation
- validators

# development dependencies required for CI
- pytest
- pytest-cov
- twine
- flake8
- cartopy
- scikit-learn

- pip
- pip:
  - pypower
  - pandapower>=2.0
  - pyomo>=5.7,<6.6.2; python_version < '3.12'
