name: pypsa-doc
channels:
- conda-forge
dependencies:
- python>=3.7
- pip
- python
- six
- numpy
- pyomo>=5.7.0
- scipy
- pandas>=1.1.0
- xarray
- netcdf4
- pytables
- matplotlib
- networkx>=2.8
- pyomo
- cartopy>=0.16
- coincbc
- glpk
- deprecation
- seaborn
- pandoc
- ipykernel   # for executing nbs

- pip:
  - .
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - nbsphinx_link
