name: pypsa-doc
channels:
- conda-forge
dependencies:
- python>=3.9
- pip
- python
- six
- numpy
- pyomo>=5.7.0
- scipy
- pandas>=1.1.0
- xarray
- netcdf4
- pytables
- matplotlib
- networkx>=2
- pyomo<6.6.2
- cartopy>=0.16
- geopandas>=0.9
- coincbc
- glpk
- deprecation
- seaborn
- pandoc
- ipykernel   # for executing nbs
- scikit-learn  # for spatial clustering
- linopy>=0.2

- pip:
  - .
  - sphinx<6
  - sphinx-book-theme
  - nbsphinx
  - nbsphinx_link
  - highspy
