name: pypsa-doc
channels:
- conda-forge
dependencies:
- python>=3.8
- pip
- python
- six
- numpy
- pyomo>=5.7.0
- scipy
- pandas>=1.1.0
- xarray
- netcdf4
- pytables
- matplotlib
- networkx>=1.10
- pyomo
- cartopy>=0.16
- coincbc
- glpk
- deprecation
- seaborn
- pandoc
- ipykernel   # for executing nbs
- scikit-learn  # for spatial clustering

- pip:
  - .
  - sphinx<6
  - sphinx-book-theme
  - nbsphinx
  - nbsphinx_link
