name: pypsa-eur
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - ipopt
  - snakemake=5.4.0=0
  - snakemake-minimal=5.4.0=py_0
  - affine=2.2.1=py_0
  - aioeasywebdav=2.2.0=py36_0
  - aiohttp=3.4.2=py36h470a237_0
  - appdirs=1.4.3=py_1
  - asn1crypto=0.24.0=py36_3
  - async-timeout=3.0.0=py36_0
  - attrs=18.2.0=py_0
  - backcall=0.1.0=py_0
  - basemap=1.2.0=py36h50ae964_0
  - basemap-data-hires=1.2.0=0
  - blas=1.1=openblas
  - blosc=1.14.4=hfc679d8_0
  - bokeh=0.13.0=py36_0
  - boost-cpp=1.67.0=h3a22d5f_0
  - boto3=1.8.5=py_0
  - botocore=1.11.6=py_0
  - bottleneck=1.2.1=py36h7eb728f_1
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.11.29=ha4d7672_0
  - cachetools=2.1.0=py_0
  - cairo=1.14.12=he6fea26_5
  - certifi=2018.11.29=py36_1000
  - cffi=1.11.5=py36h5e8e0c9_1
  - cftime=1.0.1=py36h7eb728f_0
  - chardet=3.0.4=py36_3
  - click=6.7=py_1
  - click-plugins=1.0.3=py_1
  - cligj=0.5.0=py_0
  - cloudpickle=0.5.5=py_0
  - conda-wrappers=1.0.3=py36_0
  - configargparse=0.13.0=py_1
  - cryptography=2.3.1=py36hdffb7b8_0
  - cryptography-vectors=2.3.1=py36_0
  - curl=7.61.0=h93b3f91_1
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py36h470a237_0
  - dask=0.19.0=py_0
  - dask-core=0.19.0=py_0
  - dbus=1.13.0=h3a4f0e9_0
  - decorator=4.3.0=py_0
  - descartes=1.1.0=py_2
  - distributed=1.23.0=py36_0
  - docutils=0.14=py36_1
  - dropbox=9.0.0=py_0
  - exec-wrappers=1.1.1=py_0
  - expat=2.2.5=hfc679d8_2
  - filechunkio=1.8=py_2
  - fiona=1.8.4=py36hfc77a4a_1
  - fontconfig=2.13.0=h65d0f4c_5
  - freetype=2.9.1=h6debe1e_1
  - freexl=1.0.5=hf837533_1
  - ftputil=3.4=py_0
  - gdal=2.3.2=py36hb00a9d7_0
  - geopandas=0.4.0=py_1
  - geos=3.6.2=hfc679d8_3
  - geotiff=1.4.2=hb54a4aa_2
  - gettext=0.19.8.1=0
  - giflib=5.1.4=h470a237_1
  - gitdb2=2.0.5=py_0
  - gitpython=2.1.11=py_0
  - glib=2.55.0=h464dc38_2
  - google-auth=1.5.1=py_0
  - google-auth-httplib2=0.0.2=py36_0
  - google-cloud-core=0.24.1=py36_0
  - google-cloud-storage=1.1.1=py36_0
  - google-resumable-media=0.0.2=py36_0
  - googleapis-common-protos=1.5.3=py_1
  - graphite2=1.3.12=hfc679d8_1
  - graphviz=2.38.0=h08bfae6_9
  - gst-plugins-base=1.12.5=hde13a9d_0
  - gstreamer=1.12.5=h61a6719_0
  - h5netcdf=0.6.2=py_0
  - h5py=2.8.0=py36h097b052_4
  - harfbuzz=1.8.8=h08d66d9_0
  - hdf4=4.2.13=h951d187_2
  - hdf5=1.10.3=hc401514_2
  - heapdict=1.0.0=py36_0
  - httplib2=0.11.3=py36_1
  - icu=58.2=hfc679d8_0
  - idna=2.7=py36_2
  - idna_ssl=1.0.0=0
  - ipython=7.2.0=py36h24bf2e0_1000
  - ipython_genutils=0.2.0=py_1
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py_1
  - jmespath=0.9.3=py_1
  - jpeg=9c=h470a237_1
  - json-c=0.12.1=h470a237_1
  - jsonschema=2.6.0=py36_2
  - kealib=1.4.10=hb88cf67_0
  - kiwisolver=1.0.1=py36h2d50403_2
  - krb5=1.14.6=0
  - libdap4=3.19.1=h8fe5423_1
  - libffi=3.2.1=hfc679d8_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgdal=2.3.2=hc73897a_0
  - libgfortran=3.0.0=1
  - libiconv=1.15=h470a237_3
  - libkml=1.3.0=hccc92b1_8
  - libnetcdf=4.6.1=h9cd6fdc_11
  - libpng=1.6.35=ha92aebf_1
  - libpq=9.6.3=0
  - libprotobuf=3.6.0=hd28b015_0
  - libspatialindex=1.8.5=hfc679d8_3
  - libspatialite=4.3.0a=hdfcc80b_23
  - libssh2=1.8.0=h5b517e9_2
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he6b73bb_2
  - libtool=2.4.6=h470a237_1
  - libuuid=2.32.1=h470a237_0
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_3
  - locket=0.2.0=py_2
  - lzo=2.10=0
  - markupsafe=1.0=py36h470a237_1
  - matplotlib=3.0.2=py36h8a2030e_1
  - matplotlib-base=3.0.2=py36h20b835b_1
  - memory_profiler=0.55.0=py_0
  - mkl_fft=1.0.6=py36_0
  - mkl_random=1.0.1=py36_0
  - msgpack-python=0.5.6=py36h2d50403_2
  - multidict=4.3.1=py36h470a237_0
  - munch=2.3.2=py_0
  - ncurses=6.1=hfc679d8_1
  - netcdf4=1.4.2=py36hac939d9_0
  - networkx=2.2=py_1
  - nose=1.3.7=py36_2
  - numexpr=2.6.6=py36_0
  - numpy=1.15.4=py36_blas_openblashb06ca3d_0
  - openblas=0.3.3=ha44fe06_1
  - openjpeg=2.3.0=h0e734dc_3
  - openssl=1.0.2p=h470a237_1
  - packaging=17.1=py_0
  - pandas=0.23.4=py36hf8a1672_0
  - pango=1.40.14=he752989_2
  - paramiko=2.4.1=py36_0
  - parso=0.3.1=py_0
  - partd=0.3.8=py_1
  - patsy=0.5.0=py_1
  - pcre=8.41=h470a237_2
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=18.1=py36_1000
  - pixman=0.34.0=2
  - ply=3.11=py_1
  - poppler=0.67.0=h4d7e492_3
  - poppler-data=0.4.9=0
  - postgresql=9.6.3=4
  - prettytable=0.7.2=py_2
  - proj4=4.9.3=h470a237_8
  - prompt_toolkit=2.0.7=py_0
  - protobuf=3.6.0=py36hfc679d8_0
  - psutil=5.4.7=py36h470a237_1
  - psycopg2=2.7.5=py36hdffb7b8_1
  - pthread-stubs=0.4=h470a237_1
  - ptyprocess=0.6.0=py36_0
  - pyasn1=0.4.4=py_0
  - pyasn1-modules=0.2.1=py_0
  - pycountry=18.12.8=py_0
  - pycparser=2.18=py_1
  - pygments=2.2.0=py_1
  - pygraphviz=1.4rc1=py36h470a237_0
  - pynacl=1.1.2=py36_0
  - pyomo=5.5.1=py36_1000
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py_1
  - pyproj=1.9.5.1=py36h508ed2a_6
  - pyqt=5.6.0=py36h8210e8a_7
  - pysal=1.14.4.post2=py36_0
  - pysftp=0.2.9=py_1
  - pyshp=2.0.0=py_0
  - pysocks=1.6.8=py36_2
  - pytables=3.4.4=py36h2392372_3
  - python=3.6.7=h5001a0f_1
  - python-dateutil=2.7.3=py_0
  - python-irodsclient=0.7.0=py_0
  - pytz=2018.5=py_0
  - pyutilib=5.6.3=py36_0
  - pyyaml=3.13=py36h470a237_1
  - qt=5.6.2=hf70d934_9
  - rasterio=1.0.13=py36h54a03ab_0
  - rasterstats=0.13.0=py_0
  - ratelimiter=1.2.0=py36_0
  - readline=7.0=haf1bffa_1
  - requests=2.19.1=py36_1
  - rsa=3.4.2=py_1
  - rtree=0.8.3=py36_0
  - s3transfer=0.1.13=py36_0
  - scikit-learn=0.20.2=py36_blas_openblash00c3548_400
  - scipy=1.2.0=py36_blas_openblashb06ca3d_200
  - seaborn=0.9.0=py_0
  - setuptools=40.2.0=py36_0
  - shapely=1.6.4=py36h164cb2d_1
  - simplegeneric=0.8.1=py_1
  - simplejson=3.16.0=py36h470a237_1
  - sip=4.18.1=py36hfc679d8_0
  - six=1.12.0=py36_1000
  - smmap2=2.0.5=py_0
  - snuggs=1.4.1=py_1
  - sortedcontainers=2.0.4=py_1
  - sqlalchemy=1.2.11=py36h470a237_0
  - sqlite=3.26.0=hb1c47c0_0
  - statsmodels=0.9.0=py36_0
  - tblib=1.3.2=py_1
  - tk=8.6.9=ha92aebf_0
  - toolz=0.9.0=py_0
  - tornado=5.1=py36h470a237_1
  - traitlets=4.3.2=py36_0
  - urllib3=1.23=py36_1
  - wcwidth=0.1.7=py_1
  - wheel=0.31.1=py36_1
  - wrapt=1.10.11=py36_0
  - xarray=0.11.0=py36_1000
  - xerces-c=3.2.0=0
  - xlrd=1.2.0=py_0
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.2=h8c8a85c_6
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxpm=3.5.12=h470a237_2
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-libxt=1.1.5=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - xz=5.2.4=h470a237_1
  - yaml=0.1.7=h470a237_1
  - yarl=1.2.6=py36h470a237_0
  - zict=0.1.3=py_0
  - zlib=1.2.11=h470a237_3
  - bcrypt=3.1.4=py36h14c3975_0
  - datrie=0.7.1=py36_0
  - intel-openmp=2018.0.3=0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopenblas=0.2.20=h9ac9557_7
  - mkl=2018.0.3=1
  - numpy-base=1.14.3=py36h0ea5e3f_1
  - pip:
    - pypsa>=0.13.2
    - vresutils>=0.2.5
    - git+https://github.com/FRESNA/atlite.git#egg=atlite
    - git+https://github.com/PyPSA/glaes.git#egg=glaes
    - git+https://github.com/PyPSA/geokit.git#egg=geokit

