# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-eur
channels:
  - conda-forge
  - bioconda
  - http://conda.anaconda.org/gurobi
dependencies:
  - python
  - pip
  - mamba # esp for windows build

  - pypsa>=0.17.1
  - atlite=0.0.3

  # Dependencies of the workflow itself
  - xlrd
  - openpyxl
  - scikit-learn
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - powerplantmatching>=0.4.8
  - numpy<=1.19.0 # otherwise macos fails

  # Second order dependencies which should really be deps of atlite
  - xarray
  - netcdf4
  - bottleneck
  - toolz
  - dask
  - progressbar2
  - pyyaml>=5.1.0

  # Keep in conda environment when calling ipython
  - ipython

  # GIS dependencies:
  - cartopy
  - fiona
  - proj
  - pyshp
  - geopandas
  - rasterio
  - shapely
  - libgdal<=3.0.4
  - descartes

  - pip:
    - vresutils==0.3.1
    - tsam>=1.1.0
    - git+https://github.com/PyPSA/glaes.git#egg=glaes
    - git+https://github.com/PyPSA/geokit.git#egg=geokit
    - cdsapi
